### ISSUE TITLE
Is it right to transpose rmse?

### ISSUE THREAD

**Issue by yhkee0404** [warnikchow/koremo#7]
The following code snippets all contain functions whose names are `make_data`, which transpose `rmse` conditionally on `len(S)>=mlen`. But I am not sure if that is right because a transpose's shape is the complete reverse of the original one.

https://github.com/warnikchow/koremo/blob/4c4e8106a999ee215fc4b958ffb64efce3117563/start.py#L4-L49
https://github.com/warnikchow/koremo/blob/4c4e8106a999ee215fc4b958ffb64efce3117563/koremo.py#L4-L47

Why is that not like this?:

```python
  if len(S)>=mlen: 
    data[i-1][:,:]=S[-mlen:,:] 
    data_conv[i-1][:,:,0]=S[-mlen:,:] 
    data_rmse[i-1][:,0]=rmse[-mlen:,0] 
    data_s_rmse[i-1][:,0]=rmse[-mlen:,0] 
    data_s_rmse[i-1][:,1:]=S[-mlen:,:] 
    data_s_rmse_conv[i-1][:,0,0]=rmse[-mlen:,0] 
    data_s_rmse_conv[i-1][:,1:,0]=S[-mlen:,:] 
  else: 
    data[i-1][-len(S):,:]=S 
    data_conv[i-1][-len(S):,:,0]=S 
    data_rmse[i-1][-len(S):,0]=rmse
    data_s_rmse[i-1][-len(S):,0]=rmse
    data_s_rmse[i-1][-len(S):,1:]=S 
    data_s_rmse_conv[i-1][-len(S):,0,0]=rmse
    data_s_rmse_conv[i-1][-len(S):,1:,0]=S 
```

https://github.com/warnikchow/korinto/blob/a29a3dfb96f8487d69456252ba588e0e7e1f8c7a/dist.py#L27-L81
https://github.com/warnikchow/3i4k/blob/cfa90c15f808becafca2d8ef8649b8b71f6bbe71/classify.py#L26-L82
https://github.com/warnikchow/3i4k/blob/cfa90c15f808becafca2d8ef8649b8b71f6bbe71/3i4k_demo.py#L32-L88
https://github.com/warnikchow/coaudiotext/blob/0abfbcd4dec2bdb0973122b4d6c23b9d876d8299/README.md#L67-L91

Considering one of your comments in the last code snippet, `# Padding from the back part, considering head-finality`, the conditional statement on `len(S)>=mlen` is inevitable to apply padding when its size is small.

But why is it transposed?

```python
##### Acoustic featurization
def make_data(fname,fnum,shuffle_name,mlen):
    data_s_rmse = np.zeros((fnum,mlen,129))
    for i in range(fnum):
        if i%200 ==0:
            print(i)
        num = str(shuffle_name[i])
        filename = fname+num+'.wav'
        y, sr = librosa.load(filename)
        D = np.abs(librosa.stft(y))**2
        ss, phase = librosa.magphase(librosa.stft(y))
        rmse = librosa.feature.rmse(S=ss)
        rmse = rmse/np.max(rmse)
        rmse = np.transpose(rmse)     # Normalized RMSE sequence augmented to reflect syllable-timedness
        S = librosa.feature.melspectrogram(S=D)
        S = np.transpose(S)           # Conventional mel spectrogram
        if len(S)>=mlen:              # Max frame length about 200 (~7s)
            data_s_rmse[i][:,0]=rmse[-mlen:,0]
            data_s_rmse[i][:,1:]=S[-mlen:,:]
        else:                         # Padding from the back part, considering head-finality
            data_s_rmse[i][-len(S):,0]=np.transpose(rmse)
            data_s_rmse[i][-len(S):,1:]=S
    return data_s_rmse

fem_speech = make_data('ProSem_KOR_speech/FEMALE/',3552,x_fem,200)
mal_speech = make_data('ProSem_KOR_speech/MALE/',3552,x_mal,200)
```

Is this wrong?:

```python
        if len(S)>=mlen:              # Max frame length about 200 (~7s)
            data_s_rmse[i][:,0]=rmse[-mlen:,0]
            data_s_rmse[i][:,1:]=S[-mlen:,:]
        else:                         # Padding from the back part, considering head-finality
            data_s_rmse[i][-len(S):,0]=rmse
            data_s_rmse[i][-len(S):,1:]=S
```

**Comment by yhkee0404** [comment]
I got it. It was not an issue but just an example of array broadcasting. Nothing was wrong but the above suggestions also work for a better understanding if you revise a line.

Before:

```python
  rmse = np.transpose(rmse)
```

After:

```python
  rmse = np.transpose(rmse)[:,0]
```

Then neither array broadcasting nor any additional transpose is required for `rmse`, just as in my suggestions.

**Comment by warnikchow** [comment]
Sorry for late reply :) Glad the issue was resolved.
Thanks for your nice suggestion. I will take the idea into account in next refactoring.
Have a nice day.
